import Head from 'next/head';

import AllProducts from 'sections/produk/all-product';
import TipsVideos from 'sections/produk/tips-videos';
import Review from 'sections/shared/review';

const Product = () => {
  return (
    <>
      <Head>
        <title>Produk Kami | Adelia Frozen Food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <AllProducts />
        <TipsVideos />
        <Review />
      </div>
    </>
  );
};

export default Product;
